#!/usr/bin/env bash
# Modifies the hosts file (Caution: This can break things!)

# Create new hosts file
cp /etc/hosts ~/hosts.new

# Remove any existing entries for localhost and facebook.com
sed -i '/localhost/d' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new

# Add our new entries at the beginning of the file
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Append the rest of the original hosts file (excluding our modified entries)
grep -v "localhost" /etc/hosts | grep -v "facebook.com" >> ~/hosts.new

# Replace the original hosts file
cp -f ~/hosts.new /etc/hosts